

INSERT INTO Customers (name , email , address, phone_number)
VALUES 
    ('Alice Johnson', 'alice@example.com', '456 Elm St', '555-111-2222'),
    ('Bob Smith', 'bob@example.com', '789 Oak St', '555-222-3333'),
    ('Charlie Brown', 'charlie@example.com', '123 Maple St', '555-333-4444'),
    ('David Lee', 'david@example.com', '789 Birch St', '555-444-5555'),
    ('Eve Davis', 'eve@example.com', '101 Pine St', '555-555-6666');